branch-defaults:
  main:
    environment: Finantrolapi-env
environment-defaults:
  Finantrolapi-env:
    branch: null
    repository: null
global:
  application_name: finantrolapi
  default_ec2_keyname: finantrol-ssh
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
